#ifndef EXCEPTIONS_H_INCLUDED
#define EXCEPTIONS_H_INCLUDED

#define EXCEPTION_FILE_NOT_FOUND              1
#define EXCEPTION_INSTRUCTION_NOT_FOUND       2
#define EXCEPTION_OPERAND_NOT_FOUND           3
#define EXCEPTION_OPERAND_OUT_OF_RANGE        4
#define EXCEPTION_KEYWORD_IN_FUNCTION	      5
#define EXCEPTION_ENDFUNC_OUT_OF_FUNCTION     6
#define EXCEPTION_FUNCTION_DEFINE_IN_FUNCTION 7
#define EXCEPTION_LABEL_OUT_OF_FUNCTION       8
#define EXCEPTION_INSTRUCTION_OUT_OF_FUNCTION 9

#endif // EXCEPTIONS_H_INCLUDED
